#!/bin/sh
# refered from Lecture
case "$1" in
  start)
    echo "Load aesd-char-driver"
    start-stop-daemon -S -n aesdchar_load -a /usr/bin/module_load 
    modprobe hello
    ;;
  stop)
    echo "Unload aesd-char-driver"
    start-stop-daemon -S -n aesdchar_unload -a /usr/bin/module_unload 
    rmmod hello
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
