#!/bin/sh
# refered from Lecture
case "$1" in
  start)
    echo "Loading module and skull"
    start-stop-daemon -S -n module_load -a /usr/bin/module_load -- faulty
    start-stop-daemon -S -n skull_load -a /usr/bin/skull_load
    modprobe hello
    ;;
  stop)
    echo "Unloading module and skull"
    start-stop-daemon -S -n module_unload -a /usr/bin/module_unload -- faulty
    start-stop-daemon -S -n skull_unload -a /usr/bin/skull_unload
    rmmod hello
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
